name: Generate Profile

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: RichardKBO
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Generate 3D
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: RichardKBO

      - name: Combine files
        run: |
          mkdir -p combined/profile-3d-contrib
          cp dist/* combined/
          cp profile-3d-contrib/* combined/profile-3d-contrib/

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: combined
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
