name: Generate Profile

on:
schedule:
- cron: "0 */12 * * *"

workflow_dispatch:

push:
branches:
- main

permissions:
contents: write

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  # ==============================
  # Generate GitHub Snake
  # ==============================

  - name: Generate Snake
    uses: Platane/snk@v3
    with:
      github_user_name: RichardKBO
      outputs: |
        dist/github-snake.svg
        dist/github-snake-dark.svg?palette=github-dark

  # ==============================
  # Generate 3D Contributions
  # ==============================

  - name: Generate 3D Contributions
    uses: yoshi389111/github-profile-3d-contrib@0.7.1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      USERNAME: RichardKBO

  # ==============================
  # Prepare Snake + 3D
  # ==============================

  - name: Prepare output
    run: |
      mkdir -p combined/profile-3d-contrib

      cp dist/github-snake.svg combined/
      cp dist/github-snake-dark.svg combined/

      cp profile-3d-contrib/* combined/profile-3d-contrib/

  # ==============================
  # Publish Snake + 3D
  # ==============================

  - name: Push Snake and 3D to output branch
    uses: crazy-max/ghaction-github-pages@v3
    with:
      target_branch: output
      build_dir: combined
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

trophy:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  # ==============================
  # Generate GitHub Trophy
  # ==============================

  - name: Generate GitHub Trophy
    uses: soulteary/github-profile-trophy-action@v1.0.0
    with:
      options: "username=RichardKBO&theme=tokyonight&row=1&column=6&no-frame=true&no-bg=true"
      path: profile/trophy.svg
      token: ${{ secrets.GITHUB_TOKEN }}

  # ==============================
  # Commit Trophy
  # ==============================

  - name: Commit Trophy
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      git add profile/trophy.svg

      git diff --cached --quiet || git commit -m "Update GitHub Trophy"

      git push
