name: Generate Profile

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: RichardKBO
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Generate 3D Contributions
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: RichardKBO

      - name: Generate GitHub Trophy
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=RichardKBO&theme=tokyonight&column=6&row=1&no-frame=true&no-bg=true'
          path: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare generated files
        run: |
          mkdir -p combined/profile-3d-contrib

          cp dist/github-snake.svg combined/
          cp dist/github-snake-dark.svg combined/

          cp profile-3d-contrib/* combined/profile-3d-contrib/

      - name: Publish Snake and 3D
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: combined
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/trophy.svg

          git diff --cached --quiet || git commit -m "Update GitHub Trophy"

          git push
